name: "Setup Environment"
description: "Sets up Java and Maven for the workflow"
runs:
  using: "composite"
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Grant execute permissions to Maven Wrapper
      run: chmod +x mvnw
      shell: bash
